@base_url = http://localhost:3000

###
# @name upload_asset
#
# Uploads an asset.
#

POST {{base_url}}/asset
Content-Type: image/jpeg
metadata: { "contentType": "image/jpeg", "fileName": "./test-assets/1.jpeg", "width": 4160, "height": 6240, "hash": "1234", "fileDate": "2023-02-08T01:27:01.419Z", "photoDate": "2023-02-08T01:27:01.419Z", "location": "Somewhere1", "properties": { "a": "property" } }

< ./test-assets/1.jpeg

###
#
# Uploads a thumbnail for the asset.

@upload_asset_id = {{upload_asset.response.body.assetId}}


POST {{base_url}}/thumb
Content-Type: image/jpeg
id: {{upload_asset_id}}

< ./test-assets/1.jpeg

###

POST {{base_url}}/asset
Content-Type: image/jpeg
metadata: { "contentType": "image/jpeg", "fileName": "./test-assets/2.jpeg", "width": 6336, "height": 9504, "hash": "5678", "fileDate": "2023-02-08T01:27:01.419Z", "photoDate": "2023-02-08T01:27:01.419Z", "location": "Somewhere2", "properties": { "a": "property" }  }

< ./test-assets/2.jpeg

###

POST {{base_url}}/asset
Content-Type: image/jpeg
metadata: { "contentType": "image/jpeg", "fileName": "./test-assets/3.jpeg", "width": 3361, "height": 5041, "hash": "ABCD", "fileDate": "2023-02-08T01:27:01.419Z", "photoDate": "2023-02-08T01:27:01.419Z", "location": "Somewhere3", "properties": { "a": "property" }  }

< ./test-assets/3.jpeg


###
# Retrieve an asset.
#

GET {{base_url}}/asset?id={{upload_asset_id}}

### 
# Add a label to an asset.
#

POST {{base_url}}/asset/add-label
Content-Type: application/json

{
    "id": "{{upload_asset_id}}",
    "label": "A great label"
}

### 
# Remove a label from an asset.
#

POST {{base_url}}/asset/remove-label
Content-Type: application/json

{
    "id": "{{upload_asset_id}}",
    "label": "A great label"
}


### 
# Sets a description for an asset.
#

POST {{base_url}}/asset/description
Content-Type: application/json

{
    "id": "{{upload_asset_id}}",
    "description": "A great description"
}

###
# Retrieve an thumbnail.
#

GET {{base_url}}/thumb?id={{upload_asset_id}}


###
# Check if an asset with a particular hash has been uploaded.

@hash = ABCD

GET {{base_url}}/check-asset?hash={{hash}}

###
# Retrieve a page of assets.
#

GET {{base_url}}/assets?skip=0&limit=100

###
# Search for asset.
#

GET {{base_url}}/assets?skip=0&limit=100&search=great