const std = @import("std");
const utils = @import("utils-zig");
const test_uuid_generator = utils.test_uuid_generator;
const TestUuidGenerator = test_uuid_generator.TestUuidGenerator;

//
// One golden value generated by the TypeScript implementation (see fixtures/generate.ts).
//
const GoldenUuid = struct {
    // The counter value.
    counter: i64,

    // The UUID TypeScript generates for the counter.
    uuid: []const u8,
};

//
// Returns true when `uuid` matches /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.
//
fn isUuidV4(uuid: []const u8) bool {
    if (uuid.len != 36) {
        return false;
    }
    for (uuid, 0..) |character, index| {
        if (index == 8 or index == 13 or index == 18 or index == 23) {
            if (character != '-') {
                return false;
            }
        }
        else if (!std.ascii.isDigit(character) and !(character >= 'a' and character <= 'f')) {
            return false;
        }
    }
    const variant = uuid[19];
    return uuid[14] == '4' and (variant == '8' or variant == '9' or variant == 'a' or variant == 'b');
}

test "generate() returns a non-empty string" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var generator: TestUuidGenerator = .{};

    const uuid = try generator.generate(arena.allocator());

    try std.testing.expect(uuid.len > 0);
}

test "generate() returns unique values on successive calls" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var generator: TestUuidGenerator = .{};

    const first = try generator.generate(arena.allocator());
    const second = try generator.generate(arena.allocator());

    try std.testing.expect(!std.mem.eql(u8, first, second));
}

test "generate() produces deterministic output for the same counter position" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var generator_a: TestUuidGenerator = .{};
    var generator_b: TestUuidGenerator = .{};

    const first_a = try generator_a.generate(arena.allocator());
    const second_a = try generator_a.generate(arena.allocator());
    const first_b = try generator_b.generate(arena.allocator());
    const second_b = try generator_b.generate(arena.allocator());

    try std.testing.expectEqualStrings(first_a, first_b);
    try std.testing.expectEqualStrings(second_a, second_b);
}

test "generate() returns values in standard UUID v4 string format" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var generator: TestUuidGenerator = .{};

    const uuid = try generator.generate(arena.allocator());

    try std.testing.expect(isUuidV4(uuid));
}

test "reset() restarts the counter so subsequent ids match the first sequence" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var generator: TestUuidGenerator = .{};
    const first = try generator.generate(arena.allocator());
    const second = try generator.generate(arena.allocator());

    generator.reset();
    const after_reset_first = try generator.generate(arena.allocator());
    const after_reset_second = try generator.generate(arena.allocator());

    try std.testing.expectEqualStrings(first, after_reset_first);
    try std.testing.expectEqualStrings(second, after_reset_second);
}

test "two separate instances do not share counter state" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var generator_a: TestUuidGenerator = .{};
    var generator_b: TestUuidGenerator = .{};

    const first_a = try generator_a.generate(arena.allocator());
    _ = try generator_a.generate(arena.allocator());
    const first_b = try generator_b.generate(arena.allocator());

    try std.testing.expectEqualStrings(first_a, first_b);
}

test "generateDeterministicUuid matches the TypeScript golden values" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    const golden = try std.json.parseFromSliceLeaky([]GoldenUuid, allocator, @embedFile("fixtures/test-uuid-generator.json"), .{});
    try std.testing.expect(golden.len > 50);
    for (golden) |golden_uuid| {
        const uuid = try TestUuidGenerator.generateDeterministicUuid(allocator, golden_uuid.counter);
        try std.testing.expectEqualStrings(golden_uuid.uuid, uuid);
    }
}

test "jsToUint32 and jsToInt32 follow JavaScript conversions" {
    try std.testing.expectEqual(@as(u32, 0), test_uuid_generator.jsToUint32(4294967296.0));
    try std.testing.expectEqual(@as(u32, 4294967295), test_uuid_generator.jsToUint32(-1.0));
    try std.testing.expectEqual(@as(u32, 1), test_uuid_generator.jsToUint32(1.9));
    try std.testing.expectEqual(@as(u32, 0), test_uuid_generator.jsToUint32(std.math.nan(f64)));
    try std.testing.expectEqual(@as(i32, -1431655766), test_uuid_generator.jsToInt32(0xaaaaaaaa));
    try std.testing.expectEqual(@as(i32, 1431655765), test_uuid_generator.jsToInt32(0x55555555));
}
