//
// Tests for gzipSync and gunzipSync, which compress and decompress with zlib-ng 2.3.3, the zlib Bun 1.3.14's node:zlib
// is built on (no TypeScript counterpart). The golden fixtures are generated by src/test/fixtures/generate-gzip.ts on
// Linux with Bun's `zlib.gzipSync(buffer, { level: 9 })`.
//

const std = @import("std");
const utils = @import("utils-zig");
const serialization_zig = @import("serialization-zig");
const gzip_member = @import("gzip-member.zig");
const gzipSync = serialization_zig.serialization.gzipSync;
const gunzipSync = serialization_zig.serialization.gunzipSync;
const Sha256 = std.crypto.hash.sha2.Sha256;

//
// The Io used by the tests.
//
const io = std.testing.io;

//
// Reads a fixture file.
//
fn readFixture(allocator: std.mem.Allocator, name: []const u8) ![]u8 {
    const fixture_path = try std.fmt.allocPrint(allocator, "serialization-zig/src/test/fixtures/{s}", .{name});
    return std.Io.Dir.cwd().readFileAlloc(io, fixture_path, allocator, .unlimited);
}

//
// A deterministic xorshift32 pseudo random number generator (the createRandom of fixtures/generate-gzip.ts).
//
const Random = struct {
    // The generator state.
    state: u32,

    //
    // Returns the next pseudo random number.
    //
    fn next(self: *Random) u32 {
        self.state ^= self.state << 13;
        self.state ^= self.state >> 17;
        self.state ^= self.state << 5;
        return self.state;
    }
};

//
// The words that make up the "text" inputs (the words of fixtures/generate-gzip.ts).
//
const words = [_][]const u8{
    "the",   "quick",  "brown", "fox",  "jumps",    "over",                     "lazy",      "dog",
    "photo", "sphere", "asset", "hash", "tree",     "metadata",                 "2023-01-01T00:00:00.000Z", "{\"a\":1}",
};

//
// Generates an input of the given kind and size (the generateInput of fixtures/generate-gzip.ts).
//
fn generateInput(allocator: std.mem.Allocator, kind: []const u8, size: usize, seed: u32) ![]u8 {
    var random = Random{ .state = seed };
    const output = try allocator.alloc(u8, size);
    @memset(output, 0);
    if (std.mem.eql(u8, kind, "random")) {
        for (output) |*byte| {
            byte.* = @truncate(random.next());
        }
    }
    else if (std.mem.eql(u8, kind, "text")) {
        var length: usize = 0;
        while (length < size) {
            const word = words[random.next() % words.len];
            const separator: []const u8 = if (random.next() % 8 == 0) "\n" else " ";
            for ([_][]const u8{ word, separator }) |part| {
                for (part) |character| {
                    if (length >= size) {
                        break;
                    }
                    output[length] = character;
                    length += 1;
                }
            }
        }
    }
    else if (std.mem.eql(u8, kind, "zeros")) {
        // Already zero filled.
    }
    else if (std.mem.eql(u8, kind, "pattern")) {
        const pattern = "photosphere-0123456789";
        for (output, 0..) |*byte, index| {
            byte.* = pattern[index % pattern.len];
        }
    }
    else if (std.mem.eql(u8, kind, "acgt")) {
        const alphabet = "ACGT";
        for (output) |*byte| {
            byte.* = alphabet[random.next() & 3];
        }
    }
    else if (std.mem.eql(u8, kind, "lz")) {
        var length: usize = 0;
        while (length < size) {
            if (length < 16 or random.next() % 4 == 0) {
                const count = 1 + (random.next() % 32);
                var index: u32 = 0;
                while (index < count and length < size) : (index += 1) {
                    output[length] = @truncate(random.next());
                    length += 1;
                }
            }
            else {
                const distance = 1 + (random.next() % @min(@as(u32, @intCast(length)), 40000));
                const count = 4 + (random.next() % 300);
                var index: u32 = 0;
                while (index < count and length < size) : (index += 1) {
                    output[length] = output[length - distance];
                    length += 1;
                }
            }
        }
    }
    else {
        return error.UnknownKind;
    }
    return output;
}

//
// A generated gzip case (an entry of gzip/cases.json).
//
const GzipCase = struct {
    // The kind of input.
    kind: []const u8,

    // The input size in bytes.
    size: usize,

    // The pseudo random generator seed.
    seed: u32,

    // The length of Bun's gzip output.
    length: usize,

    // The SHA-256 of Bun's gzip output (hex).
    sha256: []const u8,
};

//
// The layout of gzip/cases.json.
//
const GzipCases = struct {
    // Every generated case.
    cases: []const GzipCase,
};

test "gzipSync writes the gzip header OS byte zlib-ng's OS_CODE gives this platform (zutil.h)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    try std.testing.expectEqual(gzip_member.platformOsCode(), (try gzipSync(allocator, ""))[gzip_member.os_byte_index]);
    try std.testing.expectEqual(gzip_member.platformOsCode(), (try gzipSync(allocator, "a"))[gzip_member.os_byte_index]);
}

test "gzipSync of empty input matches Bun's gzipSync" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const expected = [_]u8{ 0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
    try gzip_member.expectGzipMemberEqual(&expected, try gzipSync(allocator, ""));
}

test "gzipSync of one byte matches Bun's gzipSync" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const expected = [_]u8{ 0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0x4b, 0x04, 0x00, 0x43, 0xbe, 0xb7, 0xe8, 0x01, 0x00, 0x00, 0x00 };
    try gzip_member.expectGzipMemberEqual(&expected, try gzipSync(allocator, "a"));
}

test "gzipSync matches Bun's gzipSync for generated inputs and gunzipSync restores them (golden)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const json = try readFixture(allocator, "gzip/cases.json");
    const parsed = try std.json.parseFromSliceLeaky(GzipCases, allocator, json, .{});
    try std.testing.expect(parsed.cases.len > 100);
    for (parsed.cases) |gzipCase| {
        const input = try generateInput(allocator, gzipCase.kind, gzipCase.size, gzipCase.seed);
        const compressed = try gzipSync(allocator, input);
        try gzip_member.expectFixtureHeader(compressed);
        // The fixture's digest covers all of Bun's output: the fixture header, then the deflate data and trailer.
        var hasher = Sha256.init(.{});
        hasher.update(&gzip_member.fixture_header);
        hasher.update(compressed[gzip_member.fixture_header.len..]);
        const digestHex = std.fmt.bytesToHex(hasher.finalResult(), .lower);
        if (compressed.len != gzipCase.length or !std.mem.eql(u8, &digestHex, gzipCase.sha256)) {
            std.debug.print("gzip output differs from Bun for {s} {d} (seed {d}): length {d}, expected {d}\n", .{ gzipCase.kind, gzipCase.size, gzipCase.seed, compressed.len, gzipCase.length });
            return error.TestExpectedEqual;
        }
        try std.testing.expectEqualSlices(u8, input, try gunzipSync(allocator, compressed));
    }
}

test "gzipSync matches Bun's gzipSync for the payload sections of every merkle tree in test/dbs and gunzipSync restores them (golden)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const fixture = try readFixture(allocator, "gzip/tree-payloads.bin");
    var reader: std.Io.Reader = .fixed(fixture);
    const count = try reader.takeInt(u32, .little);
    try std.testing.expect(count > 300);
    var index: u32 = 0;
    while (index < count) : (index += 1) {
        const name = try reader.take(try reader.takeInt(u32, .little));
        const payload = try reader.take(try reader.takeInt(u32, .little));
        const expected = try reader.take(try reader.takeInt(u32, .little));
        const compressed = try gzipSync(allocator, payload);
        gzip_member.expectGzipMemberEqual(expected, compressed) catch |err| {
            std.debug.print("gzip output differs from Bun for {s}\n", .{name});
            return err;
        };
        try std.testing.expectEqualSlices(u8, payload, try gunzipSync(allocator, expected));
    }
    try std.testing.expectEqual(@as(usize, 0), reader.bufferedLen());
}

test "gunzipSync decompresses every gzip member of concatenated members" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const concatenated = try std.mem.concat(allocator, u8, &.{ try gzipSync(allocator, "hello "), try gzipSync(allocator, "world") });
    try std.testing.expectEqualStrings("hello world", try gunzipSync(allocator, concatenated));
}

test "gunzipSync ignores trailing zero bytes after a gzip member" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const padded = try std.mem.concat(allocator, u8, &.{ try gzipSync(allocator, "hello"), &.{ 0, 0, 0, 0 } });
    try std.testing.expectEqualStrings("hello", try gunzipSync(allocator, padded));
}

test "gunzipSync decompresses output larger than one output chunk" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const input = try generateInput(allocator, "text", 100 * 1024, 7);
    try std.testing.expectEqualSlices(u8, input, try gunzipSync(allocator, try gzipSync(allocator, input)));
}

test "gunzipSync fails with zlib's message for trailing bytes that are not a gzip member" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const withGarbage = try std.mem.concat(allocator, u8, &.{ try gzipSync(allocator, "hello"), "garbage" });
    try std.testing.expectError(error.Thrown, gunzipSync(allocator, withGarbage));
    try std.testing.expectEqualStrings("incorrect header check", utils.errors.lastErrorMessage());
}

test "gunzipSync fails with Bun's unexpected end of file for empty and truncated input" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    try std.testing.expectError(error.Thrown, gunzipSync(allocator, ""));
    try std.testing.expectEqualStrings("unexpected end of file", utils.errors.lastErrorMessage());

    const compressed = try gzipSync(allocator, "hello world");
    try std.testing.expectError(error.Thrown, gunzipSync(allocator, compressed[0 .. compressed.len - 1]));
    try std.testing.expectEqualStrings("unexpected end of file", utils.errors.lastErrorMessage());
}

test "gunzipSync fails with zlib's message for a wrong uncompressed length" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const compressed = try allocator.dupe(u8, try gzipSync(allocator, "hello world"));
    compressed[compressed.len - 4] +%= 1;
    try std.testing.expectError(error.Thrown, gunzipSync(allocator, compressed));
    try std.testing.expectEqualStrings("incorrect length check", utils.errors.lastErrorMessage());
}
