const std = @import("std");
const node_utils = @import("node-utils-zig");
const TestUuidGenerator = node_utils.test_uuid_generator.TestUuidGenerator;

//
// Creates a unique directory path under the package's .zig-cache directory for test isolation.
//
fn uniqueTmpDir(allocator: std.mem.Allocator, io: std.Io) ![]const u8 {
    var random_bytes: [8]u8 = undefined;
    io.random(&random_bytes);
    return std.fmt.allocPrint(allocator, ".zig-cache/tmp/photosphere-uuid-gen-test-{x}", .{std.mem.readInt(u64, &random_bytes, .little)});
}

test "generate() succeeds and creates the counter directory when TEST_TMP_DIR does not exist" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    const io = std.testing.io;
    const tmpDir = try uniqueTmpDir(allocator, io);
    try std.testing.expect(!node_utils.fs.pathExists(io, tmpDir));

    var environ_map = std.process.Environ.Map.init(allocator);
    try environ_map.put("TEST_TMP_DIR", tmpDir);
    node_utils.process_env.setEnvironMap(&environ_map);
    defer node_utils.process_env.setEnvironMap(null);
    var generator = try TestUuidGenerator.init(allocator);

    const uuid = try generator.generate(allocator, io);

    try std.testing.expect(uuid.len > 0);
    try std.testing.expect(node_utils.fs.pathExists(io, tmpDir));

    generator.reset(io);
    try std.Io.Dir.cwd().deleteDir(io, tmpDir);
}

test "generate() returns unique values on successive calls" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    const io = std.testing.io;
    const tmpDir = try uniqueTmpDir(allocator, io);
    var environ_map = std.process.Environ.Map.init(allocator);
    try environ_map.put("TEST_TMP_DIR", tmpDir);
    node_utils.process_env.setEnvironMap(&environ_map);
    defer node_utils.process_env.setEnvironMap(null);
    var generator = try TestUuidGenerator.init(allocator);

    const first = try generator.generate(allocator, io);
    const second = try generator.generate(allocator, io);

    try std.testing.expect(!std.mem.eql(u8, first, second));

    generator.reset(io);
    try std.Io.Dir.cwd().deleteDir(io, tmpDir);
}

test "generate() continues the counter stored in the file and matches TypeScript" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    const io = std.testing.io;
    const tmpDir = try uniqueTmpDir(allocator, io);
    var environ_map = std.process.Environ.Map.init(allocator);
    try environ_map.put("TEST_TMP_DIR", tmpDir);
    node_utils.process_env.setEnvironMap(&environ_map);
    defer node_utils.process_env.setEnvironMap(null);
    var generator = try TestUuidGenerator.init(allocator);

    // Values generated by the TypeScript TestUuidGenerator for counters 1 and 2.
    try std.testing.expectEqualStrings("93694f6e-3acb-4a1c-afd2-5fb8397575a5", try generator.uuidGenerator().generate(allocator, io));

    // A second generator (like a second process) continues from the counter file.
    var other_generator = try TestUuidGenerator.init(allocator);
    try std.testing.expectEqualStrings("5c724a85-6b64-4e6a-9e15-dfa0821821e1", try other_generator.generate(allocator, io));
    const counter_text = try std.Io.Dir.cwd().readFileAlloc(io, generator.counterFilePath, allocator, .unlimited);
    try std.testing.expectEqualStrings("2", counter_text);
    try std.testing.expect(!node_utils.fs.pathExists(io, generator.lockFilePath));

    // reset() restarts the sequence.
    generator.reset(io);
    try std.testing.expectEqualStrings("93694f6e-3acb-4a1c-afd2-5fb8397575a5", try generator.generate(allocator, io));

    generator.reset(io);
    try std.Io.Dir.cwd().deleteDir(io, tmpDir);
}

test "the counter directory defaults to ./test/tmp" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    node_utils.process_env.setEnvironMap(null);
    const generator = try TestUuidGenerator.init(arena.allocator());
    try std.testing.expectEqualStrings("./test/tmp/photosphere-test-uuid-counter", generator.counterFilePath);
    try std.testing.expectEqualStrings("./test/tmp/photosphere-test-uuid-counter.lock", generator.lockFilePath);
}
