services:

  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: development
      APP_MODE: readwrite 
      AUTH_TYPE: no-auth
      ASSET_STORAGE_CONNECTION: /storage/sets
      DB_STORAGE_CONNECTION: /storage/db


        
