#!/bin/bash
DESCRIPTION="Zig CLI replicates a TypeScript encrypted database and TypeScript verifies every replica"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../../smoke-tests/lib/common.sh"
source "$SCRIPT_DIR/../lib/interop.sh"
trap cleanup_and_show_summary EXIT

test_zig_replicate_ts_encrypted_db() {
    local test_number="$1"
    print_test_header "$test_number" "ZIG REPLICATION OF A TYPESCRIPT ENCRYPTED DATABASE"

    local test_dir=$(get_test_dir "$test_number")
    local source_dir="$test_dir/encrypted-db"
    local encrypted_replica_dir="$test_dir/zig-encrypted-replica"
    local plain_replica_dir="$test_dir/zig-plain-replica"
    local reencrypted_replica_dir="$test_dir/zig-reencrypted-replica"
    local key_name="zig-rep-ts-enc-key"
    local dest_key_name="zig-rep-ts-enc-dest-key"
    local ts_cli="$(get_ts_cli_command)"
    local zig_cli="$(get_zig_cli_command)"

    check_exists "$zig_cli" "Zig CLI binary"

    # Create an encrypted database with the TypeScript CLI.
    invoke_command "Initialize encrypted database with TypeScript" "$ts_cli init --db $source_dir --key $key_name --generate-key --yes"
    invoke_command "Add PNG file with TypeScript" "$ts_cli add --db $source_dir --key $key_name $TEST_FILES_DIR/test.png --yes"
    invoke_command "Add JPG file with TypeScript" "$ts_cli add --db $source_dir --key $key_name $TEST_FILES_DIR/test.jpg --yes"

    local verify_output

    # Encrypted to encrypted with the same key.
    invoke_command "Replicate to an encrypted replica with Zig" "$zig_cli replicate --db $source_dir --dest $encrypted_replica_dir --key $key_name --dest-key $key_name --yes"
    expect_assets_encrypted "$encrypted_replica_dir"
    invoke_command "Verify the Zig encrypted replica with TypeScript" "$ts_cli verify --db $encrypted_replica_dir --key $key_name --yes" 0 "verify_output"
    expect_output_string "$verify_output" "Database verification passed - all files are intact" "TypeScript verify passes on the Zig encrypted replica"

    # Encrypted to plain.
    invoke_command "Replicate to a plain replica with Zig" "$zig_cli replicate --db $source_dir --dest $plain_replica_dir --key $key_name --yes"
    if [ -f "$plain_replica_dir/.db/encryption.pub" ]; then
        log_error "The plain replica should not contain .db/encryption.pub"
        exit 1
    fi
    invoke_command "Verify the Zig plain replica with TypeScript" "$ts_cli verify --db $plain_replica_dir --yes" 0 "verify_output"
    expect_output_string "$verify_output" "Database verification passed - all files are intact" "TypeScript verify passes on the Zig plain replica"

    # Plain to encrypted with a key generated by Zig.
    invoke_command "Replicate the plain replica to an encrypted replica with a key generated by Zig" "$zig_cli replicate --db $plain_replica_dir --dest $reencrypted_replica_dir --dest-key $dest_key_name --generate-key --yes"
    expect_assets_encrypted "$reencrypted_replica_dir"
    invoke_command "Verify the Zig re-encrypted replica with TypeScript using the Zig-generated key" "$ts_cli verify --db $reencrypted_replica_dir --key $dest_key_name --yes" 0 "verify_output"
    expect_output_string "$verify_output" "Database verification passed - all files are intact" "TypeScript verify passes on the Zig re-encrypted replica"

    test_passed
}

test_zig_replicate_ts_encrypted_db "${1:-06}"
