const std = @import("std");
const cli = @import("cli-zig");
const utils = @import("utils-zig");
const node_utils = @import("node-utils-zig");
const tools = @import("tools-zig");
const vault_zig = @import("vault-zig");
const task_queue = @import("task-queue-zig");
const helpers = @import("test-helpers.zig");
const init_cmd = cli.init_cmd;
const prompts = cli.prompts;

//
// The private key fixture (generated by TypeScript) and its public key.
//
const private_key_path = "../../packages/encryption-zig/src/test/fixtures/ts-private.pem";

//
// The public key of private_key_path.
//
const public_key_path = "../../packages/encryption-zig/src/test/fixtures/ts-public.pem";

//
// The plaintext vault directory shared by the tests of this file (getVault caches the vault).
//
var vault_dir_buffer: [std.fs.max_path_bytes]u8 = undefined;

//
// The length of the vault directory path.
//
var vault_dir_length: usize = 0;

//
// The test environment: a plaintext vault in a temporary directory.
//
const TestEnvironment = struct {
    // Owns the test's memory.
    arena: std.heap.ArenaAllocator,

    // The environment variables of the test.
    environ_map: std.process.Environ.Map,

    //
    // Sets up the environment and empties the vault.
    //
    fn init(self: *TestEnvironment) !void {
        self.arena = std.heap.ArenaAllocator.init(std.testing.allocator);
        const allocator = self.arena.allocator();
        if (vault_dir_length == 0) {
            const path = try helpers.makeTempDir(allocator, "init-cmd-vault");
            @memcpy(vault_dir_buffer[0..path.len], path);
            vault_dir_length = path.len;
        }
        const vaultDir = vault_dir_buffer[0..vault_dir_length];
        std.Io.Dir.cwd().deleteTree(std.testing.io, vaultDir) catch {};
        try std.Io.Dir.cwd().createDirPath(std.testing.io, vaultDir);
        self.environ_map = std.process.Environ.Map.init(allocator);
        try self.environ_map.put("PHOTOSPHERE_VAULT_TYPE", "plaintext");
        try self.environ_map.put("PHOTOSPHERE_VAULT_DIR", vaultDir);
        node_utils.process_env.setEnvironMap(&self.environ_map);
    }

    //
    // Restores the environment.
    //
    fn deinit(self: *TestEnvironment) void {
        node_utils.process_env.setEnvironMap(null);
        prompts.common.setDefaultStreamsForTesting(null);
        self.arena.deinit();
    }

    //
    // Stores a secret in the vault.
    //
    fn storeSecret(self: *TestEnvironment, name: []const u8, secretType: []const u8, value: []const u8) !void {
        const vault = try vault_zig.get_vault.getVault("plaintext");
        try vault.set(self.arena.allocator(), std.testing.io, .{ .name = name, .type = secretType, .value = value });
    }

    //
    // Reads a secret from the vault.
    //
    fn readSecret(self: *TestEnvironment, name: []const u8) !?vault_zig.vault.ISecret {
        const vault = try vault_zig.get_vault.getVault("plaintext");
        return vault.get(self.arena.allocator(), std.testing.io, name);
    }

    //
    // Makes the prompts read the keys and write to a discarded buffer.
    //
    fn typeKeys(self: *TestEnvironment, keys: []const u8) !void {
        const allocator = self.arena.allocator();
        const input = try helpers.chunkedInput(allocator, try helpers.splitKeys(allocator, keys));
        const output = try allocator.create(std.Io.Writer.Allocating);
        output.* = std.Io.Writer.Allocating.init(allocator);
        prompts.common.setDefaultStreamsForTesting(.{ .input = input, .output = &output.writer });
    }
};

//
// Reads a fixture file.
//
fn readFile(allocator: std.mem.Allocator, path: []const u8) ![]const u8 {
    return std.Io.Dir.cwd().readFileAlloc(std.testing.io, path, allocator, .unlimited);
}

//
// Turns text into the keys that type it into a multiline prompt (new lines become Enter).
//
fn multilineKeys(allocator: std.mem.Allocator, text: []const u8) ![]const u8 {
    const trimmed = std.mem.trimEnd(u8, text, "\n");
    const keys = try std.mem.replaceOwned(u8, allocator, trimmed, "\n", "\r");
    return std.mem.concat(allocator, u8, &.{ keys, "\x04" });
}

test "reads the environment variables when they are set, without touching the vault" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.environ_map.put("AWS_ACCESS_KEY_ID", "AKIDENV");
    try environment.environ_map.put("AWS_SECRET_ACCESS_KEY", "secretenv");
    try environment.environ_map.put("AWS_REGION", "ap-southeast-2");
    try environment.environ_map.put("AWS_ENDPOINT", "http://127.0.0.1:9000");

    const result = (try init_cmd.getDefaultS3Config(environment.arena.allocator(), std.testing.io)).?;

    try std.testing.expectEqualStrings("ap-southeast-2", result.region.?);
    try std.testing.expectEqualStrings("AKIDENV", result.accessKeyId);
    try std.testing.expectEqualStrings("secretenv", result.secretAccessKey);
    try std.testing.expectEqualStrings("http://127.0.0.1:9000", result.endpoint.?);
}

test "defaults the region when the environment names credentials but no region" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.environ_map.put("AWS_ACCESS_KEY_ID", "AKIDENV");
    try environment.environ_map.put("AWS_SECRET_ACCESS_KEY", "secretenv");

    const result = (try init_cmd.getDefaultS3Config(environment.arena.allocator(), std.testing.io)).?;

    try std.testing.expectEqualStrings("us-east-1", result.region.?);
    try std.testing.expect(result.endpoint == null);
}

test "the environment wins over the default:s3 secret, because that is the order the workers use" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();

    // The CLI's pre-flight and the worker that does the work have to resolve one path to one
    // account. When this preferred the vault, a database replicated into the bucket the
    // environment named was then reported as not existing by a command reading the same path.
    try environment.storeSecret("default:s3", "s3-credentials", "{\"region\":\"us-east-1\",\"accessKeyId\":\"AKIDVAULT\",\"secretAccessKey\":\"secretvault\",\"endpoint\":\"https://syd1.digitaloceanspaces.com\"}");
    try environment.environ_map.put("AWS_ACCESS_KEY_ID", "AKIDENV");
    try environment.environ_map.put("AWS_SECRET_ACCESS_KEY", "secretenv");
    try environment.environ_map.put("AWS_ENDPOINT", "http://127.0.0.1:9000");

    const result = (try init_cmd.getDefaultS3Config(environment.arena.allocator(), std.testing.io)).?;

    try std.testing.expectEqualStrings("AKIDENV", result.accessKeyId);
    try std.testing.expectEqualStrings("http://127.0.0.1:9000", result.endpoint.?);
}

test "falls back to the vault when only half the environment credentials are set" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.storeSecret("default:s3", "s3-credentials", "{\"region\":\"us-east-1\",\"accessKeyId\":\"AKIDVAULT\",\"secretAccessKey\":\"secretvault\",\"endpoint\":\"https://syd1.digitaloceanspaces.com\"}");
    try environment.environ_map.put("AWS_ACCESS_KEY_ID", "AKIDENV");

    const result = (try init_cmd.getDefaultS3Config(environment.arena.allocator(), std.testing.io)).?;

    try std.testing.expectEqualStrings("us-east-1", result.region.?);
    try std.testing.expectEqualStrings("AKIDVAULT", result.accessKeyId);
    try std.testing.expectEqualStrings("secretvault", result.secretAccessKey);
    try std.testing.expectEqualStrings("https://syd1.digitaloceanspaces.com", result.endpoint.?);
}

test "returns credentials when the default:s3 secret exists" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.storeSecret("default:s3", "s3-credentials", "{\"region\":\"us-east-1\",\"accessKeyId\":\"AKID123\",\"secretAccessKey\":\"secret123\",\"endpoint\":\"https://syd1.digitaloceanspaces.com\"}");
    const result = (try init_cmd.getDefaultS3Config(environment.arena.allocator(), std.testing.io)).?;
    try std.testing.expectEqualStrings("us-east-1", result.region.?);
    try std.testing.expectEqualStrings("AKID123", result.accessKeyId);
    try std.testing.expectEqualStrings("secret123", result.secretAccessKey);
    try std.testing.expectEqualStrings("https://syd1.digitaloceanspaces.com", result.endpoint.?);
}

test "returns undefined when the default:s3 secret does not exist" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try std.testing.expect(try init_cmd.getDefaultS3Config(environment.arena.allocator(), std.testing.io) == null);
}

test "returns credentials without endpoint when endpoint is not stored" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.storeSecret("default:s3", "s3-credentials", "{\"region\":\"us-east-1\",\"accessKeyId\":\"AKID123\",\"secretAccessKey\":\"secret123\"}");
    const result = (try init_cmd.getDefaultS3Config(environment.arena.allocator(), std.testing.io)).?;
    try std.testing.expect(result.endpoint == null);
    try std.testing.expectEqualStrings("AKID123", result.accessKeyId);
}

test "configureS3IfNeeded returns nothing when the AWS environment variables are set" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.environ_map.put("AWS_ACCESS_KEY_ID", "id");
    try environment.environ_map.put("AWS_SECRET_ACCESS_KEY", "secret");
    try std.testing.expect(try init_cmd.configureS3IfNeeded(environment.arena.allocator(), std.testing.io, true) == null);
}

test "configureS3IfNeeded returns the stored credentials" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.storeSecret("default:s3", "s3-credentials", "{\"region\":\"eu\",\"accessKeyId\":\"A\",\"secretAccessKey\":\"S\"}");
    const result = (try init_cmd.configureS3IfNeeded(environment.arena.allocator(), std.testing.io, true)).?;
    try std.testing.expectEqualStrings("eu", result.region.?);
}

test "configureS3IfNeeded prompts for the credentials and stores them" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    var stdout_capture = std.Io.Writer.Allocating.init(environment.arena.allocator());
    utils.console.setCapture(&stdout_capture.writer, &stdout_capture.writer);
    defer utils.console.setCapture(null, null);
    // Confirm, endpoint, region (keep the initial value), access key id, secret access key.
    try environment.typeKeys("y" ++ "https://s3.example.com\r" ++ "\r" ++ "AKID\r" ++ "shh\r");
    const result = (try init_cmd.configureS3IfNeeded(environment.arena.allocator(), std.testing.io, false)).?;
    try std.testing.expectEqualStrings("us-east-1", result.region.?);
    try std.testing.expectEqualStrings("AKID", result.accessKeyId);
    try std.testing.expectEqualStrings("shh", result.secretAccessKey);
    try std.testing.expectEqualStrings("https://s3.example.com", result.endpoint.?);
    const stored = (try environment.readSecret("default:s3")).?;
    try std.testing.expectEqualStrings("s3-credentials", stored.type);
    try std.testing.expectEqualStrings("{\"region\":\"us-east-1\",\"accessKeyId\":\"AKID\",\"secretAccessKey\":\"shh\",\"endpoint\":\"https://s3.example.com\"}", stored.value);
}

test "getAvailableKeys lists only encryption keys" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.storeSecret("my-key", "encryption-key", "pem");
    try environment.storeSecret("my-s3", "s3-credentials", "{}");
    const keys = try init_cmd.getAvailableKeys(environment.arena.allocator(), std.testing.io);
    try std.testing.expectEqual(@as(usize, 1), keys.len);
    try std.testing.expectEqualStrings("my-key", keys[0]);
}

test "selectEncryptionKey returns the selected key" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.storeSecret("alpha", "encryption-key", "pem");
    try environment.storeSecret("beta", "encryption-key", "pem");
    try environment.typeKeys("\x1b[B\r");
    const selected = try init_cmd.selectEncryptionKey(environment.arena.allocator(), std.testing.io, "Select:");
    const keys = try init_cmd.getAvailableKeys(environment.arena.allocator(), std.testing.io);
    try std.testing.expectEqualStrings(keys[1], selected);
}

test "promptForEncryption returns nothing when encryption is declined" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.typeKeys("n");
    const result = try init_cmd.promptForEncryption(environment.arena.allocator(), std.testing.io, "Encrypt?");
    try std.testing.expect(result.keyName == null);
}

test "promptForEncryption selects an existing key" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    var stdout_capture = std.Io.Writer.Allocating.init(environment.arena.allocator());
    utils.console.setCapture(&stdout_capture.writer, &stdout_capture.writer);
    defer utils.console.setCapture(null, null);
    try environment.storeSecret("existing-key", "encryption-key", "pem");
    try environment.typeKeys("y" ++ "\r" ++ "\r");
    const result = try init_cmd.promptForEncryption(environment.arena.allocator(), std.testing.io, "Encrypt?");
    try std.testing.expectEqualStrings("existing-key", result.keyName.?);
    try std.testing.expectEqual(@as(?bool, false), result.generateKey);
}

test "returns undefined in non-interactive mode" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try std.testing.expect(try init_cmd.promptToAddKey(environment.arena.allocator(), std.testing.io, "my-key", true) == null);
    try std.testing.expect(try init_cmd.promptToGenerateOrAddKey(environment.arena.allocator(), std.testing.io, "my-key", true) == null);
}

test "returns undefined when user selects cancel" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.typeKeys("\x1b[B\x1b[B\r");
    try std.testing.expect(try init_cmd.promptToAddKey(environment.arena.allocator(), std.testing.io, "my-key", false) == null);
    try std.testing.expect(try environment.readSecret("my-key") == null);
}

test "stores PEM in vault and returns key pair when user pastes PEM" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    const allocator = environment.arena.allocator();
    const privateKeyPem = try readFile(allocator, private_key_path);
    const publicKeyPem = try readFile(allocator, public_key_path);
    try environment.typeKeys(try std.mem.concat(allocator, u8, &.{ "\r", try multilineKeys(allocator, privateKeyPem) }));
    const result = (try init_cmd.promptToAddKey(allocator, std.testing.io, "my-key", false)).?;
    const pasted = std.mem.trimEnd(u8, privateKeyPem, "\n");
    try std.testing.expectEqualStrings(pasted, result.privateKeyPem);
    try std.testing.expectEqualStrings(publicKeyPem, result.publicKeyPem);
    const stored = (try environment.readSecret("my-key")).?;
    try std.testing.expectEqualStrings("encryption-key", stored.type);
    try std.testing.expectEqualStrings(pasted, stored.value);
}

test "reads PEM from file and stores in vault when user imports from file" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    const allocator = environment.arena.allocator();
    const privateKeyPem = try readFile(allocator, private_key_path);
    const publicKeyPem = try readFile(allocator, public_key_path);
    try environment.typeKeys("\x1b[B\r" ++ private_key_path ++ "\r");
    const result = (try init_cmd.promptToAddKey(allocator, std.testing.io, "my-key", false)).?;
    try std.testing.expectEqualStrings(privateKeyPem, result.privateKeyPem);
    try std.testing.expectEqualStrings(publicKeyPem, result.publicKeyPem);
    try std.testing.expectEqualStrings(privateKeyPem, (try environment.readSecret("my-key")).?.value);
}

test "generates key pair, stores in vault, and returns it when user selects generate" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    const allocator = environment.arena.allocator();
    try environment.typeKeys("\r");
    const result = (try init_cmd.promptToGenerateOrAddKey(allocator, std.testing.io, "my-key", false)).?;
    try std.testing.expect(std.mem.startsWith(u8, result.privateKeyPem, "-----BEGIN PRIVATE KEY-----\n"));
    try std.testing.expect(std.mem.startsWith(u8, result.publicKeyPem, "-----BEGIN PUBLIC KEY-----\n"));
    try std.testing.expectEqualStrings(result.privateKeyPem, (try environment.readSecret("my-key")).?.value);
}

test "returns empty array when no key name is given" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    const result = try init_cmd.resolveKeyPemsWithPrompt(environment.arena.allocator(), std.testing.io, null, false, false);
    try std.testing.expectEqual(@as(usize, 0), result.len);
}

test "returns key pems from vault when key is found without prompting" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    const allocator = environment.arena.allocator();
    const privateKeyPem = try readFile(allocator, private_key_path);
    const publicKeyPem = try readFile(allocator, public_key_path);
    try environment.storeSecret("my-key", "encryption-key", privateKeyPem);
    const result = try init_cmd.resolveKeyPemsWithPrompt(allocator, std.testing.io, "my-key", false, false);
    try std.testing.expectEqual(@as(usize, 1), result.len);
    try std.testing.expectEqualStrings(privateKeyPem, result[0].privateKeyPem);
    try std.testing.expectEqualStrings(publicKeyPem, result[0].publicKeyPem);
}

test "resolveKeyPems resolves comma-separated names and skips missing keys" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    const allocator = environment.arena.allocator();
    const privateKeyPem = try readFile(allocator, private_key_path);
    try environment.storeSecret("first", "encryption-key", privateKeyPem);
    try environment.storeSecret("not-a-key", "s3-credentials", "{}");
    const result = try init_cmd.resolveKeyPems(allocator, std.testing.io, " first , missing,not-a-key,, first");
    try std.testing.expectEqual(@as(usize, 2), result.len);
    try std.testing.expectEqual(@as(usize, 0), (try init_cmd.resolveKeyPems(allocator, std.testing.io, null)).len);
    try std.testing.expectEqual(@as(usize, 0), (try init_cmd.resolveKeyPems(allocator, std.testing.io, "")).len);
}

test "calls promptToAddKey when key is missing and canGenerate is false" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.typeKeys("\x1b[B\x1b[B\r");
    const result = try init_cmd.resolveKeyPemsWithPrompt(environment.arena.allocator(), std.testing.io, "missing-key", false, false);
    try std.testing.expectEqual(@as(usize, 0), result.len);
}

test "calls promptToGenerateOrAddKey when key is missing and canGenerate is true" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.typeKeys("\r");
    const result = try init_cmd.resolveKeyPemsWithPrompt(environment.arena.allocator(), std.testing.io, "missing-key", false, true);
    try std.testing.expectEqual(@as(usize, 1), result.len);
    try std.testing.expectEqualStrings(result[0].privateKeyPem, (try environment.readSecret("missing-key")).?.value);
}

// Phase 2: the findSimilarDatabaseNames tests (the function needs node-api-zig getDatabases).

test "returns names from fuzzyMatch when no type filter is provided" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.storeSecret("my-secret", "api-key", "val");
    try environment.storeSecret("other-secret", "encryption-key", "val");
    const result = try init_cmd.findSimilarSecretNames(environment.arena.allocator(), std.testing.io, "my-secrt", null);
    try std.testing.expectEqual(@as(usize, 1), result.len);
    try std.testing.expectEqualStrings("my-secret", result[0]);
}

test "filters by type when type is provided" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.storeSecret("my-key", "encryption-key", "pem");
    try environment.storeSecret("my-ke2", "s3-credentials", "creds");
    const result = try init_cmd.findSimilarSecretNames(environment.arena.allocator(), std.testing.io, "my-ke", "encryption-key");
    try std.testing.expectEqual(@as(usize, 1), result.len);
    try std.testing.expectEqualStrings("my-key", result[0]);
}

test "returns empty array when no secrets match" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    const result = try init_cmd.findSimilarSecretNames(environment.arena.allocator(), std.testing.io, "anything", null);
    try std.testing.expectEqual(@as(usize, 0), result.len);
}

test "only passes encryption-key entries as candidates" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.storeSecret("my-key", "encryption-key", "pem");
    try environment.storeSecret("my-kez", "s3-credentials", "creds");
    try environment.storeSecret("my-kex", "api-key", "key");
    const result = try init_cmd.findSimilarKeyNames(environment.arena.allocator(), std.testing.io, "my-ke");
    try std.testing.expectEqual(@as(usize, 1), result.len);
    try std.testing.expectEqualStrings("my-key", result[0]);
}

test "returns names returned by fuzzyMatch" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try environment.storeSecret("my-photos", "encryption-key", "pem");
    const result = try init_cmd.findSimilarKeyNames(environment.arena.allocator(), std.testing.io, "my-phtos");
    try std.testing.expectEqual(@as(usize, 1), result.len);
    try std.testing.expectEqualStrings("my-photos", result[0]);
}

test "jsNumber converts option text like Number()" {
    try std.testing.expectEqual(@as(f64, 4), init_cmd.jsNumber("4"));
    try std.testing.expectEqual(@as(f64, 1000), init_cmd.jsNumber(" 1000 "));
    try std.testing.expectEqual(@as(f64, 0), init_cmd.jsNumber(""));
    try std.testing.expect(std.math.isNan(init_cmd.jsNumber("abc")));
}

test "initContext creates the session, the worker pool and the cleanup callback" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    const allocator = environment.arena.allocator();
    const io = std.testing.io;
    const tmpDir = try helpers.makeTempDir(allocator, "init-context");
    defer std.Io.Dir.cwd().deleteTree(io, tmpDir) catch {};
    // os.tmpdir() reads TMPDIR on POSIX and TEMP on Windows (getProcessTmpDir uses it when PHOTOSPHERE_TMP_DIR is not set).
    try environment.environ_map.put("TMPDIR", tmpDir);
    try environment.environ_map.put("TEMP", tmpDir);
    try environment.environ_map.put("TEST_TMP_DIR", tmpDir);
    try environment.environ_map.put("NODE_ENV", "testing");
    const previous = utils.log.log;
    defer utils.log.setLog(previous);
    defer node_utils.termination.clearTerminationCallbacks();
    defer task_queue.queue_backend.setQueueBackend(null);
    var stdout_capture = std.Io.Writer.Allocating.init(allocator);
    utils.console.setCapture(&stdout_capture.writer, &stdout_capture.writer);
    defer utils.console.setCapture(null, null);
    cli.process_argv.setArgv(&.{ "psi", "verify" });

    const context = try init_cmd.initContext(allocator, io, .{ .workers = "3", .timeout = "5000", .verbose = true });
    try std.testing.expectEqual(@as(usize, 36), context.sessionId.len);
    const expectedDir = try std.fs.path.join(allocator, &.{ tmpDir, "photosphere", context.sessionId });
    try std.testing.expectEqualStrings(expectedDir, context.sessionTempDir);
    try std.testing.expect(node_utils.fs.pathExists(io, context.sessionTempDir));
    const pool: *cli.worker_pool.WorkerPoolBun = @ptrCast(@alignCast(context.workerPool.ptr));
    try std.testing.expectEqual(@as(f64, 3), pool.maxWorkers);
    try std.testing.expectEqual(@as(f64, 5000), pool.taskTimeout);
    const backend = try task_queue.queue_backend.getQueueBackend();
    try std.testing.expectEqual(context.workerPool.ptr, backend.ptr);
    const timestamp = context.timestampProvider.now(io);
    try std.testing.expect(timestamp >= 0);

    try node_utils.termination.invokeTerminationCallbacks(io, 0);
    try std.testing.expect(!node_utils.fs.pathExists(io, context.sessionTempDir));
    try std.testing.expect(std.mem.indexOf(u8, stdout_capture.written(), "Created temporary directory for command session: \"") != null);
    try std.testing.expect(std.mem.indexOf(u8, stdout_capture.written(), "Cleaned up temporary directory \"") != null);
}

test "initContext uses the given session ID and keeps the temporary files on failure" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    const allocator = environment.arena.allocator();
    const io = std.testing.io;
    const tmpDir = try helpers.makeTempDir(allocator, "init-context-failure");
    defer std.Io.Dir.cwd().deleteTree(io, tmpDir) catch {};
    // os.tmpdir() reads TMPDIR on POSIX and TEMP on Windows (getProcessTmpDir uses it when PHOTOSPHERE_TMP_DIR is not set).
    try environment.environ_map.put("TMPDIR", tmpDir);
    try environment.environ_map.put("TEMP", tmpDir);
    const previous = utils.log.log;
    defer utils.log.setLog(previous);
    defer node_utils.termination.clearTerminationCallbacks();
    defer task_queue.queue_backend.setQueueBackend(null);
    var stdout_capture = std.Io.Writer.Allocating.init(allocator);
    utils.console.setCapture(&stdout_capture.writer, &stdout_capture.writer);
    defer utils.console.setCapture(null, null);

    const context = try init_cmd.initContext(allocator, io, .{ .sessionId = "my-session" });
    try std.testing.expectEqualStrings("my-session", context.sessionId);
    const expectedDir = try std.fs.path.join(allocator, &.{ tmpDir, "photosphere", "my-session" });
    try std.testing.expectEqualStrings(expectedDir, context.sessionTempDir);
    const pool: *cli.worker_pool.WorkerPoolBun = @ptrCast(@alignCast(context.workerPool.ptr));
    try std.testing.expectEqual(@as(f64, 2400000), pool.taskTimeout);
    try std.testing.expectEqual(@as(f64, @floatFromInt(try std.Thread.getCpuCount())), pool.maxWorkers);

    try node_utils.termination.invokeTerminationCallbacks(io, 1);
    try std.testing.expect(node_utils.fs.pathExists(io, context.sessionTempDir));
    try std.testing.expect(std.mem.indexOf(u8, stdout_capture.written(), try std.fmt.allocPrint(allocator, "Temporary files retained for inspection: {s}\n", .{expectedDir})) != null);
}

//
// Registers databases in a fresh config dir.
//
fn registerDatabases(environment: *TestEnvironment, entries: []const @import("node-api-zig").databases_config.IDatabaseEntry) !void {
    const allocator = environment.arena.allocator();
    const configDir = try helpers.makeTempDir(allocator, "init-cmd-config");
    try environment.environ_map.put("PHOTOSPHERE_CONFIG_DIR", configDir);
    // The databases.toml that updateDatabasesConfig writes for these entries.
    var databases = std.json.Array.init(allocator);
    for (entries) |entry| {
        var tomlEntry: std.json.ObjectMap = .empty;
        try tomlEntry.put(allocator, "name", .{ .string = entry.name });
        try tomlEntry.put(allocator, "description", .{ .string = entry.description });
        try tomlEntry.put(allocator, "path", .{ .string = entry.path });
        if (entry.origin) |origin| {
            try tomlEntry.put(allocator, "origin", .{ .string = origin });
        }
        if (entry.s3Key) |s3Key| {
            try tomlEntry.put(allocator, "s3_key", .{ .string = s3Key });
        }
        if (entry.encryptionKey) |encryptionKey| {
            try tomlEntry.put(allocator, "encryption_key", .{ .string = encryptionKey });
        }
        if (entry.geocodingKey) |geocodingKey| {
            try tomlEntry.put(allocator, "geocoding_key", .{ .string = geocodingKey });
        }
        try databases.append(.{ .object = tomlEntry });
    }
    var toml: std.json.ObjectMap = .empty;
    try toml.put(allocator, "databases", .{ .array = databases });
    try toml.put(allocator, "recent_database_names", .{ .array = std.json.Array.init(allocator) });
    try @import("node-utils-zig").fs.writeToml(allocator, std.testing.io, try std.fmt.allocPrint(allocator, "{s}/databases.toml", .{configDir}), .{ .object = toml });
}

test "resolveDatabaseEntry matches the path first, then the name ignoring case" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    const allocator = environment.arena.allocator();
    try registerDatabases(&environment, &.{
        .{ .name = "Photos", .description = "", .path = "/data/photos" },
        .{ .name = "backup", .description = "", .path = "Photos" },
    });
    try std.testing.expectEqualStrings("backup", (try init_cmd.resolveDatabaseEntry(allocator, std.testing.io, "Photos")).?.name);
    try std.testing.expectEqualStrings("/data/photos", (try init_cmd.resolveDatabaseEntry(allocator, std.testing.io, "photos")).?.path);
    try std.testing.expect(try init_cmd.resolveDatabaseEntry(allocator, std.testing.io, "/other") == null);
}

test "findSimilarDatabaseNames suggests close database names" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    const allocator = environment.arena.allocator();
    try registerDatabases(&environment, &.{
        .{ .name = "my-db", .description = "", .path = "/path1" },
        .{ .name = "completely-different", .description = "", .path = "/path2" },
    });
    const similar = try init_cmd.findSimilarDatabaseNames(allocator, std.testing.io, "my-dbb");
    try std.testing.expectEqual(@as(usize, 1), similar.len);
    try std.testing.expectEqualStrings("my-db", similar[0]);
}

test "returns empty array when no databases are registered" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    try registerDatabases(&environment, &.{});
    try std.testing.expectEqual(@as(usize, 0), (try init_cmd.findSimilarDatabaseNames(environment.arena.allocator(), std.testing.io, "my-database")).len);
}

test "resolveSecretsFromEntry fetches S3 credentials only for s3 paths" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    const allocator = environment.arena.allocator();
    try environment.storeSecret("shared-s3", "s3-credentials", "{\"region\":\"eu\",\"accessKeyId\":\"A\",\"secretAccessKey\":\"S\"}");
    const s3 = try init_cmd.resolveSecretsFromEntry(allocator, std.testing.io, .{ .name = "x", .description = "", .path = "s3:bucket:/db", .s3Key = "shared-s3", .encryptionKey = "key", .geocodingKey = "geo" });
    try std.testing.expectEqualStrings("A", s3.s3Config.?.accessKeyId);
    try std.testing.expectEqualStrings("key", s3.encryptionKeyName.?);
    try std.testing.expectEqualStrings("geo", s3.geocodingKeyName.?);
    const local = try init_cmd.resolveSecretsFromEntry(allocator, std.testing.io, .{ .name = "x", .description = "", .path = "/local", .s3Key = "shared-s3" });
    try std.testing.expect(local.s3Config == null);
    try std.testing.expect(local.encryptionKeyName == null);
}

test "loadDatabase loads a database by path or registered name" {
    var environment: TestEnvironment = undefined;
    try environment.init();
    defer environment.deinit();
    const allocator = environment.arena.allocator();

    // loadDatabase exits the process when ImageMagick or ffmpeg is missing, so it needs the tools installed.
    if (!(try tools.verifyTools(allocator, std.testing.io)).allAvailable) {
        return error.SkipZigTest;
    }
    const root = try helpers.makeTempDir(allocator, "load-database");
    defer std.Io.Dir.cwd().deleteTree(std.testing.io, root) catch {};
    const dbDir = try std.fmt.allocPrint(allocator, "{s}/db", .{root});
    try helpers.copyDirectory(allocator, "../../test/dbs/v6", dbDir);
    try registerDatabases(&environment, &.{.{ .name = "MyPhotos", .description = "", .path = dbDir }});
    var stdout_capture = std.Io.Writer.Allocating.init(allocator);
    utils.console.setCapture(&stdout_capture.writer, &stdout_capture.writer);
    defer utils.console.setCapture(null, null);

    var uuidGenerator = utils.random_uuid_generator.RandomUuidGenerator{};
    var timestampProvider = utils.timestamp_provider.TimestampProvider{};
    var options: init_cmd.IBaseCommandOptions = .{ .yes = true };
    const byPath = try init_cmd.loadDatabase(allocator, std.testing.io, dbDir, &options, uuidGenerator.uuidGenerator(), timestampProvider.timestampProvider(), "session", false);
    try std.testing.expectEqualStrings(dbDir, byPath.databaseDir);
    try std.testing.expectEqualStrings("session", byPath.sessionId);
    try std.testing.expect(try byPath.assetStorage.fileExists(allocator, std.testing.io, ".db/files.dat"));

    const byName = try init_cmd.loadDatabase(allocator, std.testing.io, "myphotos", &options, uuidGenerator.uuidGenerator(), timestampProvider.timestampProvider(), "session", false);
    try std.testing.expectEqualStrings(dbDir, byName.databaseDir);
}
