import React, { createContext, useCallback, useContext, useRef, useState } from "react";

//
// An optional action button shown in the toast.
//
export interface IToastAction {
    //
    // Label for the action button.
    //
    label: string;

    //
    // Function called when the action button is clicked.
    //
    onClick: () => void;
}

//
// Represents a single toast notification.
//
export interface IToast {
    //
    // Unique identifier for the toast (auto-generated by the provider).
    //
    id: string;

    //
    // The message to display.
    //
    message: string;

    //
    // Color variant of the toast.
    //
    color: 'success' | 'warning' | 'danger' | 'neutral';

    //
    // Duration in milliseconds before auto-dismiss. 0 means no auto-dismiss.
    //
    duration: number;

    //
    // Optional action button shown alongside the message.
    //
    action?: IToastAction;
}

//
// Input type for adding a toast (id and duration are optional).
//
export type IAddToastInput = Omit<IToast, 'id' | 'duration'> & { duration?: number };

//
// Toast context value interface.
//
export interface IToastContext {
    //
    // List of currently active toasts.
    //
    toasts: IToast[];

    //
    // Adds a new toast notification. Duration defaults to 5000ms.
    //
    addToast: (toast: IAddToastInput) => void;

    //
    // Removes a toast by ID.
    //
    removeToast: (id: string) => void;
}

const ToastContext = createContext<IToastContext | undefined>(undefined);

export interface IToastContextProviderProps {
    //
    // Child components that can access the toast context.
    //
    children: React.ReactNode | React.ReactNode[];
}

//
// Provider component for the toast notification system.
//
export function ToastContextProvider({ children }: IToastContextProviderProps) {
    const [toasts, setToasts] = useState<IToast[]>([]);
    const counterRef = useRef(0);

    const addToast = useCallback((toast: IAddToastInput) => {
        counterRef.current += 1;
        const id = `toast-${counterRef.current}`;
        const newToast: IToast = {
            ...toast,
            id,
            duration: toast.duration ?? 5000,
        };
        setToasts(prev => [...prev, newToast]);
    }, []);

    const removeToast = useCallback((id: string) => {
        setToasts(prev => prev.filter(toastItem => toastItem.id !== id));
    }, []);

    return (
        <ToastContext.Provider value={{ toasts, addToast, removeToast }}>
            {children}
        </ToastContext.Provider>
    );
}

//
// Hook to access the toast context.
//
export function useToast(): IToastContext {
    const context = useContext(ToastContext);
    if (!context) {
        throw new Error(`ToastContext is not set! Add ToastContextProvider to the component tree.`);
    }
    return context;
}
