triggers:
  - paths:
      - "**/*.ts"
    commands:
      - run: bun run compile
        cooldown: 30s
        timeout: 5m    

      # - run: ./run-tests.sh
      #   cooldown: 2m
      #   timeout: 5m