//
// Generates the golden fixtures used by the Zig tests in packages/encryption-zig/src/test.
// Run from the repo root with: bun run packages/encryption-zig/src/test/fixtures/generate.ts
//
// Writes into this directory:
//   ts-private.pem, ts-public.pem       RSA-4096 key pair (pkcs8 / spki PEM) generated by node:crypto
//   ts-public-hash.hex                  hashPublicKey(publicKey) as hex
//   ts2-private.pem, ts2-public.pem     a second key pair (for multi-key maps)
//   ts2-public-hash.hex                 hashPublicKey of the second public key
//   ts-small-public.pem                 an RSA-2048 public key (spki PEM), which the file format refuses
//   plain-<size>.bin                    plaintexts (see makePlaintext; the 1 MB one is not written, Zig recreates it)
//   new-<size>.bin                      encryptBuffer(publicKey, plaintext) (PSEN format)
//   legacy-<size>.bin                   the legacy format (no header) of the same kind of payload
//                                       (the 1 MB one is not written, Zig derives it from new-1048576.bin)
//   stream-<size>.bin                   createEncryptionStream output (small sizes only)
//
import * as fs from "fs";
import * as path from "path";
import { Readable } from "stream";
import { generateKeyPairSync } from "node:crypto";
import { createEncryptionStream, encryptBuffer, exportPublicKeyToPem, generateKeyPair, hashPublicKey } from "encryption";

//
// The plaintext sizes covered by the fixtures.
//
const SIZES = [0, 1, 15, 16, 17, 1048576];

//
// Sizes whose plaintext and legacy ciphertext are not written (to keep the fixtures small).
//
const LARGE_SIZE = 1048576;

//
// The directory the fixtures are written to.
//
const fixturesDir = __dirname;

//
// Creates the deterministic plaintext of a given size: byte i is (i * 31 + 7) mod 256.
//
function makePlaintext(size: number): Buffer {
    const buffer = Buffer.alloc(size);
    for (let index = 0; index < size; index++) {
        buffer[index] = (index * 31 + 7) & 0xff;
    }
    return buffer;
}

//
// Reads a whole stream into a buffer.
//
function streamToBuffer(stream: NodeJS.ReadableStream): Promise<Buffer> {
    const chunks: Buffer[] = [];
    return new Promise((resolve, reject) => {
        stream.on("data", (chunk: Buffer) => chunks.push(chunk));
        stream.on("end", () => resolve(Buffer.concat(chunks)));
        stream.on("error", reject);
    });
}

//
// Writes one fixture file.
//
function writeFixture(fileName: string, data: string | Buffer): void {
    fs.writeFileSync(path.join(fixturesDir, fileName), data);
}

//
// Generates all fixtures.
//
async function main(): Promise<void> {
    const keyPair = generateKeyPair();
    const privateKeyPem = keyPair.privateKey.export({ type: "pkcs8", format: "pem" }) as string;
    writeFixture("ts-private.pem", privateKeyPem);
    writeFixture("ts-public.pem", exportPublicKeyToPem(keyPair.publicKey));
    writeFixture("ts-public-hash.hex", hashPublicKey(keyPair.publicKey).toString("hex"));

    const keyPair2 = generateKeyPair();
    writeFixture("ts2-private.pem", keyPair2.privateKey.export({ type: "pkcs8", format: "pem" }) as string);
    writeFixture("ts2-public.pem", exportPublicKeyToPem(keyPair2.publicKey));
    writeFixture("ts2-public-hash.hex", hashPublicKey(keyPair2.publicKey).toString("hex"));

    // 2048-bit RSA wraps the AES key into 256 bytes, which the file format cannot read back.
    const smallKeyPair = generateKeyPairSync("rsa", {
        modulusLength: 2048,
        publicKeyEncoding: {
            type: "spki",
            format: "pem",
        },
        privateKeyEncoding: {
            type: "pkcs8",
            format: "pem",
        },
    });
    writeFixture("ts-small-public.pem", smallKeyPair.publicKey);

    for (const size of SIZES) {
        const plain = makePlaintext(size);
        const encrypted = encryptBuffer(keyPair.publicKey, plain);
        writeFixture(`new-${size}.bin`, encrypted);
        if (size !== LARGE_SIZE) {
            writeFixture(`plain-${size}.bin`, plain);
            writeFixture(`legacy-${size}.bin`, encryptBuffer(keyPair.publicKey, plain).subarray(44));

            const encryptionStream = createEncryptionStream(keyPair.publicKey);
            Readable.from([plain]).pipe(encryptionStream);
            writeFixture(`stream-${size}.bin`, await streamToBuffer(encryptionStream));
        }
    }

    console.log(`Fixtures written to ${fixturesDir}`);
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
