//
// Proves that TypeScript (node:crypto) can use what the Zig port produces.
// Run by the Zig test "TypeScript decrypts Zig output and loads Zig PEM keys" (src/test/interop.test.zig) as:
//   bun run src/test/fixtures/verify-zig-output.ts <output-dir>
// The Zig test writes into <output-dir>:
//   zig-private.pem, zig-public.pem      a key pair generated by Zig (pkcs8 / spki PEM)
//   zig-public-hash.hex                  Zig hashPublicKey of that key
//   ts-public-hash-by-zig.hex            Zig hashPublicKey of the TypeScript fixture key (ts-public.pem)
//   plain-<size>.bin                     plaintexts
//   zig-new-<size>.bin                   Zig encryptBuffer with the Zig key
//   zig-ts-new-<size>.bin                Zig encryptBuffer with the TypeScript fixture key
//   zig-stream-<size>.bin                Zig createEncryptionStream output with the Zig key
// Prints "OK" and exits with 0 when every check passes, otherwise prints the failures and exits with 1.
//
import * as fs from "fs";
import * as path from "path";
import { Readable } from "stream";
import { createPrivateKey, createPublicKey, KeyObject } from "node:crypto";
import { createDecryptionStream, decryptBuffer, decryptLegacy, exportPublicKeyToPem, hashPublicKey } from "encryption";

//
// The plaintext sizes written by the Zig test.
//
const SIZES = [0, 1, 15, 16, 17, 1048576];

//
// Reads a whole stream into a buffer.
//
function streamToBuffer(stream: NodeJS.ReadableStream): Promise<Buffer> {
    const chunks: Buffer[] = [];
    return new Promise((resolve, reject) => {
        stream.on("data", (chunk: Buffer) => chunks.push(chunk));
        stream.on("end", () => resolve(Buffer.concat(chunks)));
        stream.on("error", reject);
    });
}

//
// Runs every check and returns the list of failures.
//
async function verify(outputDir: string): Promise<string[]> {
    const failures: string[] = [];
    const fixturesDir = __dirname;
    const read = (fileName: string): Buffer => fs.readFileSync(path.join(outputDir, fileName));

    const zigPrivatePem = read("zig-private.pem").toString("utf8");
    const zigPublicPem = read("zig-public.pem").toString("utf8");
    const zigPrivateKey = createPrivateKey(zigPrivatePem);
    const zigPublicKey = createPublicKey(zigPublicPem);

    if (zigPrivateKey.asymmetricKeyType !== "rsa" || zigPrivateKey.asymmetricKeyDetails?.modulusLength !== 4096) {
        failures.push("Zig private key is not RSA-4096");
    }
    if (zigPrivateKey.export({ type: "pkcs8", format: "pem" }) !== zigPrivatePem) {
        failures.push("Node re-export of the Zig private key differs from the Zig PEM");
    }
    if (exportPublicKeyToPem(zigPublicKey) !== zigPublicPem) {
        failures.push("Node re-export of the Zig public key differs from the Zig PEM");
    }
    if (exportPublicKeyToPem(createPublicKey(zigPrivateKey)) !== zigPublicPem) {
        failures.push("Public key derived by Node from the Zig private key differs from the Zig public PEM");
    }
    if (hashPublicKey(zigPublicKey).toString("hex") !== read("zig-public-hash.hex").toString("utf8")) {
        failures.push("hashPublicKey differs for the Zig key");
    }

    const tsPrivateKey = createPrivateKey(fs.readFileSync(path.join(fixturesDir, "ts-private.pem"), "utf8"));
    const tsPublicKey = createPublicKey(fs.readFileSync(path.join(fixturesDir, "ts-public.pem"), "utf8"));
    if (hashPublicKey(tsPublicKey).toString("hex") !== read("ts-public-hash-by-zig.hex").toString("utf8")) {
        failures.push("Zig hashPublicKey differs from TypeScript for the TypeScript key");
    }

    const zigKeyMap: Record<string, KeyObject> = {
        default: zigPrivateKey,
        [hashPublicKey(zigPublicKey).toString("hex")]: zigPrivateKey,
    };
    const tsKeyMap: Record<string, KeyObject> = {
        [hashPublicKey(tsPublicKey).toString("hex")]: tsPrivateKey,
    };

    for (const size of SIZES) {
        const plain = read(`plain-${size}.bin`);

        const zigEncrypted = read(`zig-new-${size}.bin`);
        if (!decryptBuffer(zigEncrypted, zigKeyMap).equals(plain)) {
            failures.push(`decryptBuffer failed for zig-new-${size}.bin`);
        }
        if (!decryptLegacy(zigEncrypted.subarray(44), zigPrivateKey).equals(plain)) {
            failures.push(`decryptLegacy failed for zig-new-${size}.bin without header`);
        }

        const zigTsEncrypted = read(`zig-ts-new-${size}.bin`);
        if (!decryptBuffer(zigTsEncrypted, tsKeyMap).equals(plain)) {
            failures.push(`decryptBuffer failed for zig-ts-new-${size}.bin`);
        }

        const zigStream = read(`zig-stream-${size}.bin`);
        const decryptionStream = createDecryptionStream(zigKeyMap);
        Readable.from([zigStream]).pipe(decryptionStream);
        if (!(await streamToBuffer(decryptionStream)).equals(plain)) {
            failures.push(`createDecryptionStream failed for zig-stream-${size}.bin`);
        }
    }

    return failures;
}

//
// Entry point.
//
async function main(): Promise<void> {
    const outputDir = process.argv[2];
    if (!outputDir) {
        console.error("Usage: bun run verify-zig-output.ts <output-dir>");
        process.exit(1);
    }
    const failures = await verify(outputDir);
    if (failures.length > 0) {
        for (const failure of failures) {
            console.error(failure);
        }
        process.exit(1);
    }
    console.log("OK");
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
