//
// Generates the golden fixtures used by the cloudflare-zlib-deflate unit tests (cloudflare-zlib-deflate.test.zig).
// Run from the repo root with: bun run packages/serialization-zig/src/test/fixtures/generate-gzip.ts
//
// Every expected value is produced by Bun's `zlib.gzipSync(buffer, { level: 9 })` (what the TypeScript serialization
// package calls), so the Zig tests prove the Zig gzip output is byte-identical to what the TypeScript CLI writes:
// - gzip/cases.json: generated inputs (described by kind, size and seed, regenerated by the Zig test with the same
//   pseudo random generator) with the length and SHA-256 of Bun's gzip output.
// - gzip/tree-payloads.bin: the uncompressed payload sections of every merkle tree in test/dbs (as TypeScript saveTree
//   writes them today) with Bun's gzip output of each.
//

import * as fs from "fs";
import * as path from "path";
import { createHash } from "crypto";
import { gunzipSync, gzipSync } from "zlib";
import { loadTree, saveTree } from "merkle-tree";
import { FileStorage } from "storage";

//
// The directory this script lives in (fixtures are written next to it).
//
const fixturesDir = path.dirname(new URL(import.meta.url).pathname);

//
// The repo's test databases.
//
const testDbsDir = path.resolve(fixturesDir, "../../../../../test/dbs");

//
// Throws when a condition does not hold (sanity checks on the TypeScript side).
//
function assert(condition: boolean, message: string): void {
    if (!condition) {
        throw new Error(`Fixture sanity check failed: ${message}`);
    }
}

//
// A deterministic xorshift32 pseudo random number generator (mirrored by the Zig test).
//
function createRandom(seed: number): () => number {
    let state = seed >>> 0;
    return () => {
        state ^= state << 13;
        state >>>= 0;
        state ^= state >>> 17;
        state ^= state << 5;
        state >>>= 0;
        return state;
    };
}

//
// The words that make up the "text" inputs.
//
const words = [
    "the", "quick", "brown", "fox", "jumps", "over", "lazy", "dog",
    "photo", "sphere", "asset", "hash", "tree", "metadata", "2023-01-01T00:00:00.000Z", "{\"a\":1}",
];

//
// Generates an input of the given kind and size (mirrored by the Zig test).
//
function generateInput(kind: string, size: number, seed: number): Buffer {
    const random = createRandom(seed);
    const output = Buffer.alloc(size);
    if (kind === "random") {
        for (let index = 0; index < size; index++) {
            output[index] = random() & 0xff;
        }
    }
    else if (kind === "text") {
        let length = 0;
        while (length < size) {
            const word = words[random() % words.length] + (random() % 8 === 0 ? "\n" : " ");
            for (let index = 0; index < word.length && length < size; index++) {
                output[length] = word.charCodeAt(index);
                length++;
            }
        }
    }
    else if (kind === "zeros") {
        // Buffer.alloc zero fills.
    }
    else if (kind === "pattern") {
        const pattern = "photosphere-0123456789";
        for (let index = 0; index < size; index++) {
            output[index] = pattern.charCodeAt(index % pattern.length);
        }
    }
    else if (kind === "acgt") {
        const alphabet = "ACGT";
        for (let index = 0; index < size; index++) {
            output[index] = alphabet.charCodeAt(random() & 3);
        }
    }
    else if (kind === "lz") {
        let length = 0;
        while (length < size) {
            if (length < 16 || random() % 4 === 0) {
                const count = 1 + (random() % 32);
                for (let index = 0; index < count && length < size; index++) {
                    output[length] = random() & 0xff;
                    length++;
                }
            }
            else {
                const distance = 1 + (random() % Math.min(length, 40000));
                const count = 4 + (random() % 300);
                for (let index = 0; index < count && length < size; index++) {
                    output[length] = output[length - distance];
                    length++;
                }
            }
        }
    }
    else {
        throw new Error(`Unknown kind ${kind}`);
    }
    return output;
}

//
// A generated gzip case (an entry of gzip/cases.json).
//
interface IGzipCase {
    // The kind of input.
    kind: string;

    // The input size in bytes.
    size: number;

    // The pseudo random generator seed.
    seed: number;

    // The length of Bun's gzip output.
    length: number;

    // The SHA-256 of Bun's gzip output (hex).
    sha256: string;
}

//
// gzip/cases.json: Bun's gzip output of generated inputs of every kind, at sizes around the deflate window (32K), the
// sliding window buffer (64K), the symbol buffer (16K symbols) and above 1MB.
//
function generateCases(): void {
    const sizes = [
        0, 1, 2, 3, 4, 5, 8, 100, 257, 258, 259, 262, 263, 1000,
        16383, 16384, 16385, 32505, 32506, 32507, 32767, 32768, 32769,
        65535, 65536, 65537, 131072, 131073, 200000,
    ];
    const kinds = ["random", "text", "zeros", "pattern", "acgt", "lz"];
    const cases: IGzipCase[] = [];
    let seed = 1;
    const add = (kind: string, size: number) => {
        const input = generateInput(kind, size, seed);
        const compressed = gzipSync(input, { level: 9 });
        assert(gunzipSync(compressed).equals(input), `round trip of ${kind} ${size}`);
        cases.push({ kind, size, seed, length: compressed.length, sha256: createHash("sha256").update(compressed).digest("hex") });
        seed++;
    };
    for (const kind of kinds) {
        for (const size of sizes) {
            add(kind, size);
        }
    }
    for (const kind of ["random", "text", "zeros", "pattern", "lz"]) {
        add(kind, 1100000);
    }
    fs.mkdirSync(path.join(fixturesDir, "gzip"), { recursive: true });
    fs.writeFileSync(path.join(fixturesDir, "gzip/cases.json"), JSON.stringify({ cases }, null, 1) + "\n");
}

//
// Returns the type code TypeScript loads a merkle tree file of test/dbs with, or undefined when the file is not a
// merkle tree (sort index trees and the hash cache).
//
function treeTypeCode(relativePath: string): string | undefined {
    if (relativePath.includes("/indexes/") || relativePath.includes("/sort_indexes/") || path.basename(relativePath).startsWith("hash-cache")) {
        return undefined;
    }
    const baseName = path.basename(relativePath);
    if (baseName === "files.dat" || baseName === "tree.dat") {
        return "FTRE";
    }
    if (baseName === "db.dat") {
        return "BDBT";
    }
    return "COLT";
}

//
// Lists every file under a directory (relative paths, sorted).
//
function listFiles(directory: string, relativeDirectory: string): string[] {
    const files: string[] = [];
    for (const entry of fs.readdirSync(path.join(directory, relativeDirectory), { withFileTypes: true })) {
        const relativePath = path.join(relativeDirectory, entry.name);
        if (entry.isDirectory()) {
            files.push(...listFiles(directory, relativePath));
        }
        else {
            files.push(relativePath);
        }
    }
    return files.sort();
}

//
// Minimal in-memory storage with the read/write methods used by saveTree.
//
class MemoryStorage {
    // Files stored by path.
    files = new Map<string, Buffer>();

    // Reads a file (undefined when missing).
    async read(filePath: string): Promise<Buffer | undefined> {
        return this.files.get(filePath);
    }

    // Writes a file.
    async write(filePath: string, contentType: string | undefined, data: Buffer): Promise<void> {
        this.files.set(filePath, data);
    }
}

//
// Returns the three gzip sections of a version 6 tree file:
// [u32 version][4 byte type][u32 BSON length][BSON metadata][16 byte id][u32 length][gzip string table][u32 hash count][hashes]
// [u32 length][gzip sort tree][u32 length][gzip merkle tree][32 byte checksum].
//
function treeGzipSections(file: Buffer): Buffer[] {
    let offset = 8;
    offset += 4 + file.readUInt32LE(offset);
    offset += 16;
    const sections: Buffer[] = [];
    const readSection = () => {
        const length = file.readUInt32LE(offset);
        sections.push(file.subarray(offset + 4, offset + 4 + length));
        offset += 4 + length;
    };
    readSection();
    const hashCount = file.readUInt32LE(offset);
    offset += 4 + hashCount * 32;
    readSection();
    readSection();
    assert(offset + 32 === file.length, "tree file layout");
    return sections;
}

//
// gzip/tree-payloads.bin: [u32 count] then for each section [u32 name length][name][u32 payload length][payload]
// [u32 gzip length][gzip], all little endian.
//
async function generateTreePayloads(): Promise<void> {
    const fileStorage = new FileStorage("");
    const memoryStorage = new MemoryStorage();
    const parts: Buffer[] = [];
    let count = 0;
    const writeUInt32 = (value: number) => {
        const buffer = Buffer.alloc(4);
        buffer.writeUInt32LE(value);
        parts.push(buffer);
    };
    const writeBlock = (data: Buffer) => {
        writeUInt32(data.length);
        parts.push(data);
    };
    for (const relativePath of listFiles(testDbsDir, "")) {
        if (!relativePath.endsWith(".dat")) {
            continue;
        }
        const typeCode = treeTypeCode(relativePath);
        if (!typeCode) {
            continue;
        }
        const tree = await loadTree(path.join(testDbsDir, relativePath), fileStorage, typeCode);
        assert(tree !== undefined && !tree.dirty, `load ${relativePath}`);
        await saveTree("tree.dat", tree!, memoryStorage as any, typeCode);
        const sections = treeGzipSections(memoryStorage.files.get("tree.dat")!);
        const sectionNames = ["string-table", "sort-tree", "merkle-tree"];
        sections.forEach((section, index) => {
            const payload = gunzipSync(section);
            const compressed = gzipSync(payload, { level: 9 });
            assert(compressed.equals(section), `gzipSync of ${relativePath} ${sectionNames[index]} equals what saveTree wrote`);
            writeBlock(Buffer.from(`${relativePath}#${sectionNames[index]}`));
            writeBlock(payload);
            writeBlock(compressed);
            count++;
        });
    }
    const countBuffer = Buffer.alloc(4);
    countBuffer.writeUInt32LE(count);
    fs.writeFileSync(path.join(fixturesDir, "gzip/tree-payloads.bin"), Buffer.concat([countBuffer, ...parts]));
    console.log(`Wrote ${count} tree payload sections`);
}

//
// Generates every gzip fixture.
//
async function main(): Promise<void> {
    console.log(`zlib ${process.versions.zlib}`);
    generateCases();
    await generateTreePayloads();
    console.log(`Wrote gzip fixtures to ${fixturesDir}/gzip`);
}

main().catch(error => {
    console.error(error);
    process.exit(1);
});
