//
// Byte-level parity of saved tree files with the TypeScript merkle-tree package (no TypeScript counterpart).
// The fixtures are generated by src/test/fixtures/generate-saved-trees.ts (run with bun from the repo root):
// - saved-trees.bin: every merkle tree in test/dbs loaded and saved again by TypeScript.
// - buffer-collisions.json: BufferSet and BufferMap iteration order after operations on hashes that share XOR buckets.
// - collision-tree.json and collision-tree.dat: a tree whose content hashes share XOR buckets, saved by TypeScript.
//

const std = @import("std");
const merkle_tree_zig = @import("merkle-tree-zig");
const memory_storage = @import("memory-storage.zig");
const gzip_fixture_os_byte = @import("gzip-fixture-os-byte.zig");
const merkle_tree = merkle_tree_zig.merkle_tree;
const BufferSet = merkle_tree_zig.buffer_set.BufferSet;
const BufferMap = merkle_tree_zig.buffer_map.BufferMap;
const IMerkleTree = merkle_tree.IMerkleTree;
const MemoryStorage = memory_storage.MemoryStorage;

//
// The Io used by the tests.
//
const io = std.testing.io;

//
// The directory of the fixtures (tests run with the package directory as cwd).
//
const FIXTURES_DIR = "src/test/fixtures";

//
// The repo's test databases, relative to the package directory.
//
const TEST_DBS_DIR = "../../test/dbs";

//
// Reads a fixture file.
//
fn readFixture(allocator: std.mem.Allocator, name: []const u8) ![]u8 {
    const fixturePath = try std.fmt.allocPrint(allocator, "{s}/{s}", .{ FIXTURES_DIR, name });
    return std.Io.Dir.cwd().readFileAlloc(io, fixturePath, allocator, .unlimited);
}

//
// Loads a tree from bytes through the in-memory storage.
//
fn loadTreeBytes(allocator: std.mem.Allocator, bytes: []const u8, typeCode: []const u8) !IMerkleTree {
    var storage = MemoryStorage.init(allocator);
    try storage.putFile("tree.dat", bytes);
    return (try merkle_tree.loadTree(allocator, io, "tree.dat", storage.asStorage(), typeCode)).?;
}

//
// Saves a tree and returns the bytes of the file.
//
fn saveTreeBytes(allocator: std.mem.Allocator, tree: *const IMerkleTree, typeCode: []const u8) ![]const u8 {
    var storage = MemoryStorage.init(allocator);
    try merkle_tree.saveTree(allocator, io, "tree.dat", tree, storage.asStorage(), typeCode);
    return storage.getFile("tree.dat").?;
}

//
// Parses lowercase hex.
//
fn fromHex(allocator: std.mem.Allocator, text: []const u8) ![]const u8 {
    const bytes = try allocator.alloc(u8, text.len / 2);
    _ = try std.fmt.hexToBytes(bytes, text);
    return bytes;
}

//
// Formats bytes as lowercase hex.
//
fn toHex(allocator: std.mem.Allocator, bytes: []const u8) ![]const u8 {
    return std.fmt.allocPrint(allocator, "{x}", .{bytes});
}

//
// An operation on a BufferSet and a BufferMap (ICollisionStep in generate-saved-trees.ts).
//
const CollisionStep = struct {
    // "add", "delete" or "clear".
    op: []const u8,

    // The hash as hex.
    hash: []const u8,

    // The value passed to BufferMap.set.
    value: u32,

    // The hashes BufferSet.values() iterates after the operation (hex).
    setOrder: []const []const u8,

    // The "hash:value" entries BufferMap.entries() iterates after the operation.
    mapOrder: []const []const u8,

    // What delete returned on the BufferSet and BufferMap.
    deleted: []const u8,
};

//
// The layout of buffer-collisions.json.
//
const CollisionSteps = struct {
    // Every step.
    steps: []const CollisionStep,
};

//
// An item of collision-tree.json.
//
const CollisionItem = struct {
    // The item name.
    name: []const u8,

    // The item hash as hex.
    hash: []const u8,

    // The item length.
    length: u64,

    // The item last modified time in milliseconds.
    lastModified: i64,
};

//
// The layout of collision-tree.json.
//
const CollisionTree = struct {
    // The tree id.
    treeId: []const u8,

    // The items added in order.
    items: []const CollisionItem,
};

test "saves every tree in test/dbs byte-identical to TypeScript saveTree" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const fixture = try readFixture(allocator, "saved-trees.bin");
    var reader: std.Io.Reader = .fixed(fixture);
    const count = try reader.takeInt(u32, .little);
    try std.testing.expect(count > 100);
    var index: u32 = 0;
    while (index < count) : (index += 1) {
        const relativePath = try reader.take(try reader.takeInt(u32, .little));
        const typeCode = try reader.take(try reader.takeInt(u32, .little));
        const expected = try reader.take(try reader.takeInt(u32, .little));

        const filePath = try std.fmt.allocPrint(allocator, "{s}/{s}", .{ TEST_DBS_DIR, relativePath });
        const original = try std.Io.Dir.cwd().readFileAlloc(io, filePath, allocator, .unlimited);
        const tree = try loadTreeBytes(allocator, original, typeCode);
        const actual = try gzip_fixture_os_byte.normaliseSavedFileGzipOsBytes(allocator, try saveTreeBytes(allocator, &tree, typeCode));
        if (!std.mem.eql(u8, expected, actual)) {
            std.debug.print("Saved tree differs from TypeScript: {s}\n", .{relativePath});
            return error.TestExpectedEqual;
        }
    }
    try std.testing.expectEqual(@as(usize, 0), reader.bufferedLen());
}

test "saves the trees TypeScript saved for the scenarios byte-identical" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    for ([_][]const u8{ "empty", "files", "names", "records", "shards" }) |name| {
        const expected = try readFixture(allocator, try std.fmt.allocPrint(allocator, "scenario-{s}.dat", .{name}));
        const tree = try loadTreeBytes(allocator, expected, "FTRE");
        std.testing.expectEqualSlices(u8, expected, try gzip_fixture_os_byte.normaliseSavedFileGzipOsBytes(allocator, try saveTreeBytes(allocator, &tree, "FTRE"))) catch |err| {
            std.debug.print("Saved scenario tree differs from TypeScript: {s}\n", .{name});
            return err;
        };
    }
}

test "BufferSet and BufferMap iterate hashes that share XOR buckets in TypeScript order" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const json = try readFixture(allocator, "buffer-collisions.json");
    const fixture = try std.json.parseFromSliceLeaky(CollisionSteps, allocator, json, .{});
    var set = BufferSet.init(allocator);
    var map = BufferMap(u32).init(allocator);
    var addCount: usize = 0;
    for (fixture.steps) |step| {
        // Only the leading "add" steps are replayed: delete and clear are not ported (not reached by psi replicate
        // or psi verify).
        if (!std.mem.eql(u8, step.op, "add")) {
            break;
        }
        const hash = try fromHex(allocator, step.hash);
        _ = try set.add(hash);
        _ = try map.set(hash, step.value);
        addCount += 1;

        var setValueIterator = set.values();
        var setValueList: std.ArrayList([]const u8) = .empty;
        while (setValueIterator.next()) |value| {
            try setValueList.append(allocator, value);
        }
        const setValues = setValueList.items;
        try std.testing.expectEqual(step.setOrder.len, setValues.len);
        for (step.setOrder, setValues) |expected, actual| {
            try std.testing.expectEqualStrings(expected, try toHex(allocator, actual));
        }

        // Every "hash:value" entry TypeScript iterates is found in the map.
        for (step.mapOrder) |expectedEntry| {
            const separatorIndex = std.mem.indexOfScalar(u8, expectedEntry, ':').?;
            const entryHash = try fromHex(allocator, expectedEntry[0..separatorIndex]);
            const entryValue = try std.fmt.parseInt(u32, expectedEntry[separatorIndex + 1 ..], 10);
            try std.testing.expectEqual(@as(?u32, entryValue), try map.get(entryHash));
        }
    }
    try std.testing.expect(addCount > 0);
}

test "saves a tree whose content hashes share XOR buckets byte-identical to TypeScript" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const json = try readFixture(allocator, "collision-tree.json");
    const fixture = try std.json.parseFromSliceLeaky(CollisionTree, allocator, json, .{});
    const expected = try readFixture(allocator, "collision-tree.dat");

    var tree = merkle_tree.createTree(fixture.treeId);
    for (fixture.items) |item| {
        tree = try merkle_tree.addItem(allocator, &tree, .{
            .name = item.name,
            .hash = try fromHex(allocator, item.hash),
            .length = item.length,
            .lastModified = item.lastModified,
        });
    }
    tree.merkle = try merkle_tree.buildMerkleTree(allocator, tree.sort);
    tree.dirty = false;
    try std.testing.expectEqualSlices(u8, expected, try gzip_fixture_os_byte.normaliseSavedFileGzipOsBytes(allocator, try saveTreeBytes(allocator, &tree, "FTRE")));

    // Loading the TypeScript file and saving it again gives the same bytes.
    const loaded = try loadTreeBytes(allocator, expected, "FTRE");
    try std.testing.expectEqualSlices(u8, expected, try gzip_fixture_os_byte.normaliseSavedFileGzipOsBytes(allocator, try saveTreeBytes(allocator, &loaded, "FTRE")));
}
