//
// Tests for the gzip level 9 port of Bun's bundled Cloudflare zlib (no TypeScript counterpart).
// The golden fixtures are generated by src/test/fixtures/generate-gzip.ts with Bun's `zlib.gzipSync(buffer, { level: 9 })`.
//

const std = @import("std");
const serialization_zig = @import("serialization-zig");
const cloudflare_zlib_deflate = serialization_zig.cloudflare_zlib_deflate;
const gzip_fixture_os_byte = @import("gzip-fixture-os-byte.zig");
const builtin = @import("builtin");
const Sha256 = std.crypto.hash.sha2.Sha256;

//
// The Io used by the tests.
//
const io = std.testing.io;

//
// Reads a fixture file.
//
fn readFixture(allocator: std.mem.Allocator, name: []const u8) ![]u8 {
    const fixture_path = try std.fmt.allocPrint(allocator, "src/test/fixtures/{s}", .{name});
    return std.Io.Dir.cwd().readFileAlloc(io, fixture_path, allocator, .unlimited);
}

//
// Decompresses gzip data with the Zig standard library.
//
fn gunzip(allocator: std.mem.Allocator, compressed: []const u8) ![]u8 {
    var input: std.Io.Reader = .fixed(compressed);
    var decompressor = std.compress.flate.Decompress.init(&input, .gzip, &.{});
    return decompressor.reader.allocRemaining(allocator, .unlimited);
}

//
// A deterministic xorshift32 pseudo random number generator (the createRandom of fixtures/generate-gzip.ts).
//
const Random = struct {
    // The generator state.
    state: u32,

    //
    // Returns the next pseudo random number.
    //
    fn next(self: *Random) u32 {
        self.state ^= self.state << 13;
        self.state ^= self.state >> 17;
        self.state ^= self.state << 5;
        return self.state;
    }
};

//
// The words that make up the "text" inputs (the words of fixtures/generate-gzip.ts).
//
const words = [_][]const u8{
    "the",   "quick",  "brown", "fox",  "jumps",    "over",                     "lazy",      "dog",
    "photo", "sphere", "asset", "hash", "tree",     "metadata",                 "2023-01-01T00:00:00.000Z", "{\"a\":1}",
};

//
// Generates an input of the given kind and size (the generateInput of fixtures/generate-gzip.ts).
//
fn generateInput(allocator: std.mem.Allocator, kind: []const u8, size: usize, seed: u32) ![]u8 {
    var random = Random{ .state = seed };
    const output = try allocator.alloc(u8, size);
    @memset(output, 0);
    if (std.mem.eql(u8, kind, "random")) {
        for (output) |*byte| {
            byte.* = @truncate(random.next());
        }
    }
    else if (std.mem.eql(u8, kind, "text")) {
        var length: usize = 0;
        while (length < size) {
            const word = words[random.next() % words.len];
            const separator: []const u8 = if (random.next() % 8 == 0) "\n" else " ";
            for ([_][]const u8{ word, separator }) |part| {
                for (part) |character| {
                    if (length >= size) {
                        break;
                    }
                    output[length] = character;
                    length += 1;
                }
            }
        }
    }
    else if (std.mem.eql(u8, kind, "zeros")) {
        // Already zero filled.
    }
    else if (std.mem.eql(u8, kind, "pattern")) {
        const pattern = "photosphere-0123456789";
        for (output, 0..) |*byte, index| {
            byte.* = pattern[index % pattern.len];
        }
    }
    else if (std.mem.eql(u8, kind, "acgt")) {
        const alphabet = "ACGT";
        for (output) |*byte| {
            byte.* = alphabet[random.next() & 3];
        }
    }
    else if (std.mem.eql(u8, kind, "lz")) {
        var length: usize = 0;
        while (length < size) {
            if (length < 16 or random.next() % 4 == 0) {
                const count = 1 + (random.next() % 32);
                var index: u32 = 0;
                while (index < count and length < size) : (index += 1) {
                    output[length] = @truncate(random.next());
                    length += 1;
                }
            }
            else {
                const distance = 1 + (random.next() % @min(@as(u32, @intCast(length)), 40000));
                const count = 4 + (random.next() % 300);
                var index: u32 = 0;
                while (index < count and length < size) : (index += 1) {
                    output[length] = output[length - distance];
                    length += 1;
                }
            }
        }
    }
    else {
        return error.UnknownKind;
    }
    return output;
}

//
// A generated gzip case (an entry of gzip/cases.json).
//
const GzipCase = struct {
    // The kind of input.
    kind: []const u8,

    // The input size in bytes.
    size: usize,

    // The pseudo random generator seed.
    seed: u32,

    // The length of Bun's gzip output.
    length: usize,

    // The SHA-256 of Bun's gzip output (hex).
    sha256: []const u8,
};

//
// The layout of gzip/cases.json.
//
const GzipCases = struct {
    // Every generated case.
    cases: []const GzipCase,
};

test "gzipLevel9 writes the gzip header OS byte zlib's OS_CODE gives this platform (zutil.h)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const expected: u8 = switch (builtin.os.tag) {
        .macos => 19,
        .windows => 10,
        else => 3,
    };
    try std.testing.expectEqual(expected, cloudflare_zlib_deflate.os_code);
    try std.testing.expectEqual(expected, (try cloudflare_zlib_deflate.gzipLevel9(allocator, ""))[9]);
    try std.testing.expectEqual(expected, (try cloudflare_zlib_deflate.gzipLevel9(allocator, "a"))[9]);
}

test "gzipLevel9 of empty input is byte-identical to Bun's gzipSync" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const expected = [_]u8{ 0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
    try std.testing.expectEqualSlices(u8, &expected, try gzip_fixture_os_byte.normaliseGzipOsBytes(allocator, try cloudflare_zlib_deflate.gzipLevel9(allocator, "")));
}

test "gzipLevel9 of one byte is byte-identical to Bun's gzipSync" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const expected = [_]u8{ 0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0x4b, 0x04, 0x00, 0x43, 0xbe, 0xb7, 0xe8, 0x01, 0x00, 0x00, 0x00 };
    try std.testing.expectEqualSlices(u8, &expected, try gzip_fixture_os_byte.normaliseGzipOsBytes(allocator, try cloudflare_zlib_deflate.gzipLevel9(allocator, "a")));
}

test "gzipLevel9 is byte-identical to Bun's gzipSync for generated inputs (golden)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const json = try readFixture(allocator, "gzip/cases.json");
    const parsed = try std.json.parseFromSliceLeaky(GzipCases, allocator, json, .{});
    try std.testing.expect(parsed.cases.len > 100);
    for (parsed.cases) |gzipCase| {
        const input = try generateInput(allocator, gzipCase.kind, gzipCase.size, gzipCase.seed);
        const compressed = try cloudflare_zlib_deflate.gzipLevel9(allocator, input);
        var digest: [Sha256.digest_length]u8 = undefined;
        Sha256.hash(try gzip_fixture_os_byte.normaliseGzipOsBytes(allocator, compressed), &digest, .{});
        const digestHex = std.fmt.bytesToHex(digest, .lower);
        if (compressed.len != gzipCase.length or !std.mem.eql(u8, &digestHex, gzipCase.sha256)) {
            std.debug.print("gzip output differs from Bun for {s} {d} (seed {d}): length {d}, expected {d}\n", .{ gzipCase.kind, gzipCase.size, gzipCase.seed, compressed.len, gzipCase.length });
            return error.TestExpectedEqual;
        }
        try std.testing.expectEqualSlices(u8, input, try gunzip(allocator, compressed));
    }
}

test "gzipLevel9 is byte-identical to Bun's gzipSync for the payload sections of every merkle tree in test/dbs (golden)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const fixture = try readFixture(allocator, "gzip/tree-payloads.bin");
    var reader: std.Io.Reader = .fixed(fixture);
    const count = try reader.takeInt(u32, .little);
    try std.testing.expect(count > 300);
    var index: u32 = 0;
    while (index < count) : (index += 1) {
        const name = try reader.take(try reader.takeInt(u32, .little));
        const payload = try reader.take(try reader.takeInt(u32, .little));
        const expected = try reader.take(try reader.takeInt(u32, .little));
        const compressed = try cloudflare_zlib_deflate.gzipLevel9(allocator, payload);
        if (!std.mem.eql(u8, expected, try gzip_fixture_os_byte.normaliseGzipOsBytes(allocator, compressed))) {
            std.debug.print("gzip output differs from Bun for {s}\n", .{name});
            return error.TestExpectedEqual;
        }
    }
    try std.testing.expectEqual(@as(usize, 0), reader.bufferedLen());
}
