name: Frontend Deploy
on:
  push:
    branches: 
      - main
    paths:
      - frontend/**
      - packages/user-interface/**

  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      VERSION: ${{github.sha}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.5

      # - name: Get pnpm cache directory
      #   id: pnpm-cache-dir
      #   run: echo "::set-output name=dir::$(pnpm cache dir)"

      # - name: Cache pnpm modules
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ steps.pnpm-cache-dir.outputs.dir }}
      #     key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-

      - name: Install Dependencies
        run: pnpm install

      - name: Compile code
        run: pnpm run compile

      - name: Build frontend
        working-directory: frontend
        run: pnpm run build

      - name: Create version file
        working-directory: frontend
        run: |
          echo "{ \"version\": \"${VERSION}\" }" > ./dist/version.json

      #
      # Configures the AWS cli.
      #
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      #
      # Deploys to static web page to s3.
      #
      - name: Deploy to S3
        run: aws s3 cp ./frontend/build s3://${{secrets.FRONTEND_S3_BUCKET}}/ --recursive

